# Generated by Django 4.1.7 on 2023-03-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_short_dscription_product_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
